### ISSUE TITLE
Flows stopped due to missing node types.  mqtt-plus-broker

### ISSUE THREAD

**Issue by yewmin** [btsimonh/node-red-contrib-mqtt-plus#1]
I'm not sure why this command is popping up please help!
![Capture](https://user-images.githubusercontent.com/77000368/103636572-25e5e480-4f85-11eb-949f-923b748bb5e1.PNG)

**Comment by btsimonh** [comment]
what NR version are you on?
Do you have the boot logs?

**Comment by yewmin** [comment]
Sorry im new to node-red... how do i check the NR version?

And the boot log: 
5 Jan 19:57:10 - [warn] ------------------------------------------------------
5 Jan 19:57:10 - [warn] [node-red-contrib-mqtt-plus/mqtt-plus] Error: Cannot find module 'mqtt'
Require stack:
- C:\Users\yewmi\downloads\node-red-contrib-mqtt-plus-master\mqtt-plus.js
- C:\Users\yewmi\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\registry\lib\loader.js
- C:\Users\yewmi\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\registry\lib\index.js
- C:\Users\yewmi\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\nodes\index.js
- C:\Users\yewmi\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\index.js
- C:\Users\yewmi\AppData\Roaming\npm\node_modules\node-red\lib\red.js
- C:\Users\yewmi\AppData\Roaming\npm\node_modules\node-red\red.js
5 Jan 19:57:10 - [warn] ------------------------------------------------------

**Comment by btsimonh** [comment]
hmm... it is strange that it's getting it from here:
C:\Users\yewmi\downloads\node-red-contrib-mqtt-plus-master\mqtt-plus.js
I'm sure that is not the right place.  should be under some /local folder, not direct from your download location.

Locate your Node-Red local folder, go there, then

npm install C:\Users\yewmi\downloads\node-red-contrib-mqtt-plus-master

I'm not so familiar with 'standard' installations of NodeJS.....  I never install globally.

**Comment by btsimonh** [comment]
also, unless you ned very specifically my extra features, the 'normal' mqtt node does most of it now (e.g. WSS: etc.).  mine only adds stuff like dynamic user/pwd, extra info about failures.

**Comment by yewmin** [comment]
ohh i see okay... but now i have an issue when i did npm uninstall on the files in ~/.node-red and the same message pops out is there anyway to fully remove the file from .node-red?

**Comment by yewmin** [comment]
when i try to remove from node red palette it shows this message:

Failed to remove: node-red-contrib-mqtt-plus

Type in use: mqtt-plus-broker

Check the log for more information

**Comment by btsimonh** [comment]
I would kill the node process, then rename/delete the C:\Users\yewmi\downloads\node-red-contrib-mqtt-plus-master folder, and start again.

**Comment by yewmin** [comment]
I delete all the flows and deleted the folder but the message from first comment still pops out
![aaaa](https://user-images.githubusercontent.com/77000368/103647543-73b71880-4f96-11eb-90e4-f91402b988eb.PNG)

**Comment by yewmin** [comment]
5 Jan 20:39:07 - [info] Waiting for missing types to be registered:
5 Jan 20:39:07 - [info]  - mqtt-plus-broker 

shows up on cmd when node-red is started

**Comment by btsimonh** [comment]
somehow it's cached the used nodes :(.
you no longer see:
5 Jan 19:57:10 - [warn] [node-red-contrib-mqtt-plus/mqtt-plus] Error: Cannot find module 'mqtt'

did you go into 'configuration nodes' and kill it there? (these are 'global' nodes, apply to all flows, and so don't get deleted when you delete flows)

**Comment by yewmin** [comment]
i deleted everything related to mqtt plus in the json files but it still shows up.

could it be due to this warning:
5 Jan 20:52:41 - [warn]

---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.

If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.

You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------

5 Jan 20:52:41 - [info] Waiting for missing types to be registered:
5 Jan 20:52:41 - [info]  - mqtt-plus-broker

**Comment by btsimonh** [comment]
no, it always throws that credential warning.
try renaming config.json and config.json.backup, and flows.json.backup, and re-check inside flows.json.

**Comment by yewmin** [comment]
I have managed to solve the problem i just deleted all the codes in the JSON files and reinstalled node-red all together thanks for your help!
